### ISSUE TITLE
How can I make multiple calls from client?

### ISSUE THREAD

**Issue by alfonsoabad** [demchenkoe/node-amqp-rpc#2]
for example if I want to make a call every single second, this code won't work 

``` javascript
setInterval(function() {
rpc.call('say.hello', { name: 'John' }, function(msg) {
        console.log('results of say.Hello:', msg);
    });
}, 1000);
```

I stays waiting after the first console.log(), 
do I need to disconnect after each call, 

thanks

**Comment by robraux** [comment]
The way the code is currently setup, I could only get multiple calls to function by using the factory. You could would need to look like:

``` javascript
setInterval(function() {
var rpc = require('amqp-rpc').factory({url: amqpConfig.url})

rpc.call('say.hello', { name: 'John' }, function(msg) {
        console.log('results of say.Hello:', msg);
    });
}, 1000);
```

Think of it as one factory call for every rpc.call. Worked perfectly for me then. Not sure if that's the original author's intention or not. Hopefully they will comment.

**Comment by alfonsoabad** [comment]
Yeah, I tested your example and worked, but I have lots of conecctions remain running. How can I close them?
http://imageshack.us/f/38/screenshot20121025at945.png/

**Comment by alfonsoabad** [comment]
Ok I see that once you  terminate the script all connections that remain running are closed, but I would like to have a way to reuse the connection. don't know if that is posible, for me it makes more sense but I'm still a rabbitMQ noob

**Comment by robraux** [comment]
You are correct, however that doesn't seems like the right long term answer. Neither is utilizing a single queue for every RPC request. We're utilizing this internally for a new project which is just getting off the ground. For the moment this library is good enough to serve the purpose, however we will be revisiting it within the next 2 weeks to review and clean up issues like this. In the meantime, anything you work on regarding this I'm greatly interested in.

**Comment by demchenkoe** [comment]
Hello guys. This issue was fixed. Thanks about interests and error detection.

**Comment by robraux** [comment]
Cheers @demchenkoe. This should allow one factory call, then multiple rpc.call's, correct? Like @alfonsoabad original example?

**Comment by demchenkoe** [comment]
Yes, it is. )

**Comment by alfonsoabad** [comment]
Thanks, it works now, tested 4 instances of the example sending message every single 0.1 ms , I got 2700 msg/s  aprox without increasing memory consumption, so cool. 
I opened a new issue to ask how to close the connection.
