### ISSUE TITLE
Sometimes server can't receive command

### ISSUE THREAD

**Issue by mongris** [demchenkoe/node-amqp-rpc#5]
I implemented a very simple demo with your amqp rpc module, it is easy to use, thank you!

But sometimes the rpc server can't receive client command.
I noticed that all of the queues is not durable.

https://github.com/demchenkoe/node-amqp-rpc/blob/8b65148e241116b27aa0d48f38cfbb8d018b2de8/index.js#L258

If I set the command queues with `{ durable: true, autoDelete: false }` and all works well.

Does it make sense if I set all of the command queues with `{ durable: true, autoDelete: false }`?

**Comment by demchenkoe** [comment]
Yes, of course.

By default, we have the usual RPC protocol behavior. 
You can customize the possibility of RMQ as you need it.
